### ISSUE TITLE
Theme Vibrant Ink is missing

### ISSUE THREAD

**Issue by ashgreat** [bkam235/ThemeSwitcher#1]
I am using Rstudio 1.1.383 on Mac. I use "Vibant Ink" dark theme which I don't see in your list of valid themes. I hope you add this in future.

<img width="590" alt="image" src="https://user-images.githubusercontent.com/6580738/43104156-dc905c26-8ea6-11e8-8c14-6fc79950e337.png">

**Comment by bkam235** [comment]
Added "Vibrant Ink". Must have missed it initially.
The current solution is somewhat brittle, because valid themes are listed as a char string in the package variables. Haven't yet found a way to pull a list of available editor themes from the RStudio API.

**Comment by ashgreat** [comment]
> Added "Vibrant Ink". Must have missed it initially.
> The current solution is somewhat brittle, because valid themes are listed as a char string in the package variables. Haven't yet found a way to pull a list of available editor themes from the RStudio API.

Thanks! Works great!
